connections {
    JED {
        remote_addrs = 212.11.160.226
        version = 2
        proposals = aes256-sha256-modp2048
        rekey_time = 8h
        local {
            auth = psk
            id = noc.samirgroup.net
        }
        remote {
            auth = psk
            id = 212.11.160.226
        }
        children {
            JED {
                local_ts = 172.22.0.0/24
                remote_ts = 10.1.0.0/22
                esp_proposals = aes256-sha256-modp2048
                dpd_action = restart
                start_action = start
            }
            JED-2 {
                local_ts = 172.22.0.0/24
                remote_ts = 10.1.8.0/24
                esp_proposals = aes256-sha256-modp2048
                dpd_action = restart
                start_action = start
            }
        }
    }
}

secrets {
    ike-JED {
        id-0 = noc.samirgroup.net
        id-1 = 212.11.160.226
        secret = "Admin@2025"
    }
}
