connections {
    RYD {
        remote_addrs = 212.11.165.194
        version = 2
        proposals = aes256-sha256-modp2048
        rekey_time = 8h
        local {
            auth = psk
            id = noc.samirgroup.net
        }
        remote {
            auth = psk
            id = 212.11.165.194
        }
        children {
            RYD {
                local_ts = 172.22.0.0/24
                remote_ts = 10.2.0.0/22
                esp_proposals = aes256-sha256-modp2048
                dpd_action = restart
                start_action = start
            }
            RYD-2 {
                local_ts = 172.22.0.0/24
                remote_ts = 10.2.88.0/24
                esp_proposals = aes256-sha256-modp2048
                dpd_action = restart
                start_action = start
            }
        }
    }
}

secrets {
    ike-RYD {
        id-0 = noc.samirgroup.net
        id-1 = 212.11.165.194
        secret = "Admin@2025"
    }
}
