<?php
/**
 * SG_NOC Branch VM — SNMP device list sync.
 *
 * Pulls the operator-curated device list for this branch from the NOC,
 * renders /etc/telegraf/telegraf.d/50-snmp-devices.conf using the
 * appropriate per-device-type template, and reloads Telegraf if the
 * rendered config changed.
 *
 * Run by sg-noc-snmp-sync.timer every 5 minutes. Idempotent — a run
 * that produces no diff exits 0 with no telegraf reload.
 */

declare(strict_types=1);

const ENV_FILE     = '/etc/sg-noc-branch.env';
const TEMPLATE_DIR = '/opt/sg-noc-branch/telegraf/templates';
const OUTPUT_FILE  = '/etc/telegraf/telegraf.d/50-snmp-devices.conf';
const STATE_FILE   = '/var/lib/sg-noc-branch/snmp-sync.json';

$env       = parse_env_file(ENV_FILE);
$noc_url   = rtrim($env['NOC_URL'] ?? '', '/');
$token     = $env['API_TOKEN']      ?? '';
$branch_id = $env['BRANCH_ID']      ?? '';

if ($noc_url === '' || $token === '' || $branch_id === '') {
    fwrite(STDERR, "ERROR: NOC_URL / API_TOKEN / BRANCH_ID missing in " . ENV_FILE . "\n");
    exit(1);
}

// ─── Fetch this branch's device list from the NOC ─────────────────────────
$ch = curl_init("$noc_url/api/branch-config/snmp-devices");
curl_setopt_array($ch, [
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_TIMEOUT        => 15,
    CURLOPT_CONNECTTIMEOUT => 5,
    CURLOPT_HTTPHEADER     => [
        "Authorization: Bearer $token",
        "Accept: application/json",
    ],
]);
$body = curl_exec($ch);
$code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
$err  = curl_error($ch);
curl_close($ch);

if ($code !== 200) {
    fwrite(STDERR, "ERROR: NOC fetch failed (HTTP $code) " . ($err ?: '') . "\n");
    exit(2);
}

$data = json_decode((string) $body, true);
if (!is_array($data) || ($data['ok'] ?? false) !== true) {
    fwrite(STDERR, "ERROR: unexpected response from NOC\n");
    exit(2);
}

$devices = is_array($data['devices'] ?? null) ? $data['devices'] : [];

// ─── Render the Telegraf config from per-type templates ──────────────────
$out  = "# Auto-generated by sg-noc-snmp-sync.service. Do not hand-edit.\n";
$out .= "# Last sync: " . gmdate('c') . " — " . count($devices) . " device(s)\n\n";

$skipped = 0;
foreach ($devices as $d) {
    $type = (string) ($d['device_type'] ?? '');
    $tpl  = TEMPLATE_DIR . "/{$type}.toml";
    if (!is_file($tpl)) {
        fwrite(STDERR, "WARN: no template for device_type='$type', skipping {$d['name']}\n");
        $skipped++;
        continue;
    }

    $rendered = strtr((string) file_get_contents($tpl), [
        '__HOST__'          => (string) ($d['host']               ?? ''),
        '__PORT__'          => (string) ($d['snmp_port']          ?? 161),
        '__COMMUNITY__'     => escape_toml_string((string) ($d['snmp_community']     ?? '')),
        '__NAME__'          => escape_toml_string((string) ($d['name']               ?? '')),
        '__POLL_INTERVAL__' => (string) ($d['polling_interval_s'] ?? 60),
        '__BRANCH__'        => escape_toml_string($branch_id),
    ]);

    $out .= "\n# ─── {$d['name']} — {$d['host']} ($type) ───────────\n";
    $out .= $rendered . "\n";
}

// ─── Compare and write only if changed ───────────────────────────────────
$existing = is_file(OUTPUT_FILE) ? (string) file_get_contents(OUTPUT_FILE) : '';
$same     = hash('sha256', $existing) === hash('sha256', $out);

@mkdir(dirname(STATE_FILE), 0755, true);

if ($same) {
    fwrite(STDOUT, "no-change: " . count($devices) . " device(s), $skipped skipped\n");
    save_state([
        'last_sync_at' => gmdate('c'),
        'devices'      => count($devices),
        'skipped'      => $skipped,
        'reloaded'     => false,
    ]);
    exit(0);
}

$tmp = OUTPUT_FILE . '.tmp';
if (file_put_contents($tmp, $out) === false) {
    fwrite(STDERR, "ERROR: cannot write $tmp\n");
    exit(3);
}
chmod($tmp, 0644);
rename($tmp, OUTPUT_FILE);

// ─── Reload Telegraf to pick up the new config ──────────────────────────
exec('systemctl reload-or-restart telegraf 2>&1', $reloadOut, $rc);
if ($rc !== 0) {
    fwrite(STDERR, "ERROR: telegraf reload failed:\n" . implode("\n", $reloadOut) . "\n");
    save_state([
        'last_sync_at' => gmdate('c'),
        'devices'      => count($devices),
        'skipped'      => $skipped,
        'reloaded'     => false,
        'error'        => 'telegraf reload failed',
    ]);
    exit(4);
}

fwrite(STDOUT, "synced: " . count($devices) . " device(s), $skipped skipped, telegraf reloaded\n");
save_state([
    'last_sync_at' => gmdate('c'),
    'devices'      => count($devices),
    'skipped'      => $skipped,
    'reloaded'     => true,
]);
exit(0);

// ─── Helpers ──────────────────────────────────────────────────────────────

function parse_env_file(string $path): array
{
    $out = [];
    if (!is_readable($path)) return $out;
    foreach (file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
        if ($line === '' || $line[0] === '#' || !str_contains($line, '=')) continue;
        [$k, $v] = explode('=', $line, 2);
        $out[trim($k)] = trim($v, "\"' \t");
    }
    return $out;
}

/**
 * Escape a string so it's safe inside a TOML double-quoted value.
 * Telegraf TOML follows the standard TOML spec; we only need to escape
 * \ and " inside strings.
 */
function escape_toml_string(string $s): string
{
    return str_replace(['\\', '"'], ['\\\\', '\\"'], $s);
}

function save_state(array $state): void
{
    @file_put_contents(STATE_FILE, json_encode($state, JSON_UNESCAPED_SLASHES) . "\n");
}
