@extends('layouts.admin')

@section('title', 'Remote Browser — Session')

@section('content')
{{-- Inline styles: the admin layout has @stack('scripts') but not @stack('head'),
     so @push('head') would be silently dropped. --}}
<style>
    body.browser-portal-session { overflow: hidden !important; }
    body.browser-portal-session main,
    body.browser-portal-session .container,
    body.browser-portal-session .container-fluid,
    body.browser-portal-session .py-4 { padding: 0 !important; margin: 0 !important; max-width: none !important; }
    .bp-frame-wrap {
        position: fixed;
        inset: 56px 0 0 0;       /* leave the existing top navbar visible */
        background: #000;
        z-index: 1020;
    }
    .bp-frame-wrap iframe {
        display: block;
        width: 100%; height: 100%; border: 0;
    }
    .bp-toolbar {
        position: absolute; top: 8px; right: 8px; z-index: 1030;
        display: flex; gap: 8px;
    }
</style>
<div class="bp-frame-wrap">
    <div class="bp-toolbar">
        <a href="{{ route('admin.browser-portal.index') }}" class="btn btn-sm btn-secondary">
            <i class="bi bi-arrow-left me-1"></i>Back
        </a>
        <form method="POST" action="{{ route('admin.browser-portal.destroy', $session->session_id) }}">
            @csrf
            @method('DELETE')
            <button class="btn btn-sm btn-danger" type="submit"
                    onclick="return confirm('Stop this session?')">
                <i class="bi bi-stop-circle me-1"></i>Stop
            </button>
        </form>
    </div>

    {{-- Neko's multiuser provider supports auto-login via ?pwd= URL param.
         The per-session user password is generated by SessionManager and
         decrypted server-side in the controller — never exposed to the user. --}}
    <iframe src="/s/{{ $session->session_id }}/{{ $nekoPassword ? '?pwd=' . urlencode($nekoPassword) : '' }}"
            allow="autoplay; clipboard-read; clipboard-write; fullscreen; microphone; camera; display-capture"
            referrerpolicy="same-origin"></iframe>
</div>

<script>
(function () {
    document.body.classList.add('browser-portal-session');

    // 60s heartbeat so the 4h idle cutoff only fires when the tab is really idle.
    const url = @json(route('admin.browser-portal.heartbeat'));
    const sid = @json($session->session_id);
    const token = document.querySelector('meta[name="csrf-token"]')?.content;

    async function beat() {
        if (document.hidden) return;
        try {
            await fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': token || '',
                    'Accept': 'application/json',
                },
                body: JSON.stringify({ session_id: sid }),
                credentials: 'same-origin',
            });
        } catch (_) { /* swallow: next beat will retry */ }
    }
    beat();
    setInterval(beat, 60_000);
})();
</script>
@endsection
