[program:switch-poll]
command=php /var/www/sgnoc/artisan schedule:run
directory=/var/www/sgnoc
autostart=true
autorestart=true
stderr_logfile=/var/log/sgnoc/switch-poll.err.log
stdout_logfile=/var/log/sgnoc/switch-poll.out.log
user=www-data
