[program:switch-poll]
command=php /home/azureuser/phonebook2/artisan schedule:run
directory=/home/azureuser/phonebook2
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/supervisor/switch-poll.err.log
stdout_logfile=/var/log/supervisor/switch-poll.out.log
user=azureuser
