[program:vq-collector]
command=php /var/www/sgnoc/artisan vq:collect --port=5099
directory=/var/www/sgnoc
autostart=true
autorestart=true
stderr_logfile=/var/log/sgnoc/vq-collector.err.log
stdout_logfile=/var/log/sgnoc/vq-collector.out.log
user=www-data
