[program:vq-collector]
command=php /home/azureuser/phonebook2/artisan vq:collect --port=5099
directory=/home/azureuser/phonebook2
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/supervisor/vq-collector.err.log
stdout_logfile=/var/log/supervisor/vq-collector.out.log
user=azureuser
