<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Jobs\SendPrinterSetupEmailJob;
use App\Models\ActivityLog;
use App\Models\Employee;
use App\Models\Printer;
use App\Models\PrinterDeployToken;
use App\Models\PrinterDriver;
use App\Services\Identity\GraphService;
use App\Services\PrinterScriptService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class PrinterDeployController extends Controller
{
    /**
     * POST /admin/printer-deploy/deploy
     * Send a printer setup link to an employee's email.
     */
    public function deploy(Request $request): RedirectResponse
    {
        $data = $request->validate([
            'employee_id' => 'required|integer|exists:employees,id',
        ]);

        $employee = Employee::with('branch')->findOrFail($data['employee_id']);

        if (empty($employee->email)) {
            return back()->withErrors(['employee_id' => 'This employee has no email address on record.']);
        }

        if (! $employee->branch_id) {
            return back()->withErrors(['employee_id' => 'This employee has no branch assigned.']);
        }

        $token = PrinterDeployToken::create([
            'employee_id'   => $employee->id,
            'branch_id'     => $employee->branch_id,
            'token'         => Str::random(64),
            'expires_at'    => now()->addDays(7),
            'sent_to_email' => $employee->email,
        ]);

        SendPrinterSetupEmailJob::dispatch($token->id)->onQueue('emails');

        return back()->with('success', 'Printer setup link sent to ' . $employee->email);
    }

    /**
     * POST /admin/printer-deploy/intune
     * Push a PowerShell script to Intune for the given printer.
     */
    public function deployToIntune(Request $request): RedirectResponse
    {
        $data = $request->validate([
            'printer_id'     => 'required|exists:printers,id',
            'azure_group_id' => 'nullable|string|max:100',
        ]);

        $printer = Printer::with('branch')->findOrFail($data['printer_id']);
        $driver  = PrinterDriver::findForPrinter($printer, 'windows_x64');
        $ps1     = (new PrinterScriptService())->generateIntunePowerShell($printer, $driver);

        $displayName = 'SG NOC - Printer - ' . ($printer->branch?->name ?? 'Unknown') . ' - ' . $printer->printer_name;

        try {
            $graph     = new GraphService();
            $intuneId  = $graph->uploadIntuneScript($displayName, $ps1, 'Auto-generated by SG NOC');
            $printer->update(['intune_script_id' => $intuneId]);

            if (! empty($data['azure_group_id'])) {
                $graph->assignIntuneScriptToGroup($intuneId, $data['azure_group_id']);
            }

            ActivityLog::create([
                'model_type' => 'Printer',
                'model_id'   => $printer->id,
                'action'     => 'intune_deploy',
                'changes'    => ['intune_script_id' => $intuneId],
                'user_id'    => Auth::id(),
            ]);

            return back()->with('success', "Deployed to Intune. Script ID: {$intuneId}");
        } catch (\Throwable $e) {
            return back()->withErrors(['intune' => 'Intune deployment failed: ' . $e->getMessage()]);
        }
    }

    /**
     * POST /admin/printer-deploy/intune-remove
     * Remove a printer's script from Intune.
     */
    public function removeFromIntune(Request $request): RedirectResponse
    {
        $data    = $request->validate(['printer_id' => 'required|exists:printers,id']);
        $printer = Printer::findOrFail($data['printer_id']);

        if ($printer->intune_script_id) {
            try {
                $graph = new GraphService();
                $graph->deleteIntuneScript($printer->intune_script_id);
            } catch (\Throwable $e) {
                // Log but continue — script may already be deleted in Intune
            }
            $printer->update(['intune_script_id' => null]);
        }

        return back()->with('success', 'Removed from Intune.');
    }

    /**
     * GET /admin/printer-deploy/intune-preview?printer_id=X
     * Return the PS1 script content for preview before deploying.
     */
    public function intunePreview(Request $request): JsonResponse
    {
        $data    = $request->validate(['printer_id' => 'required|exists:printers,id']);
        $printer = Printer::with('branch')->findOrFail($data['printer_id']);
        $driver  = PrinterDriver::findForPrinter($printer, 'windows_x64');
        $ps1     = (new PrinterScriptService())->generateIntunePowerShell($printer, $driver);

        return response()->json([
            'ps1_content'      => $ps1,
            'driver_name'      => $driver?->driver_name ?? 'Microsoft IPP Class Driver (fallback)',
            'driver_version'   => $driver?->version,
            'has_driver_file'  => (bool) $driver?->driver_file_path,
            'intune_script_id' => $printer->intune_script_id,
        ]);
    }

    /**
     * GET /admin/printer-deploy/script-preview?printer_id=X&os=windows
     * Return the .bat or .sh script content for preview.
     */
    public function scriptPreview(Request $request): JsonResponse
    {
        $data = $request->validate([
            'printer_id' => 'required|exists:printers,id',
            'os'         => 'required|in:windows,mac',
        ]);

        $printer = Printer::with('branch')->findOrFail($data['printer_id']);
        $osType  = $data['os'] === 'mac' ? 'mac' : 'windows_x64';
        $driver  = PrinterDriver::findForPrinter($printer, $osType);
        $service = new PrinterScriptService();

        $content = $data['os'] === 'mac'
            ? $service->generateMacSh($printer, $driver)
            : $service->generateWindowsBat($printer, $driver);

        return response()->json([
            'script'          => $content,
            'has_driver'      => (bool) $driver,
            'has_driver_file' => (bool) $driver?->driver_file_path,
            'deploy_type'     => $driver?->driver_file_path ? 'zip_with_driver' : 'script_only',
        ]);
    }
}
